name: deploy-prod
on:
  workflow_dispatch:
jobs:
  deploy-to-k8s:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.6.3

      - name: Set k8s context
        uses: Azure/k8s-set-context@v4
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Set up Tailscale VPN
        uses: tailscale/github-action@v3
        with:
          authkey: ${{ secrets.TAILSCALE_KEY }}
          args: --login-server=https://headscale.morjoff.com

      - name: Deploy to Kubernetes with Helm
        run: |
          helm upgrade --install --atomic --values helm/values.yaml \
            --set appImage.tag=${{ github.sha }} \
            --set dbImage.tag=${{ github.sha }} \
            --set "env.RESERVIO_URL=${{ secrets.RESERVIO_URL }}" \
            --set "env.TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" \
            --set "env.TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}" \
            reservio-slot-seeker helm
